CREATE SCHEMA Enterprise DEFAULT CHARACTER SET utf8;

USE Enterprise;

CREATE TABLE Employee (
	Id INT PRIMARY KEY AUTO_INCREMENT,
	`Name` VARCHAR(255),
	`User` VARCHAR(255),
	`Password` VARCHAR(255),
	CONSTRAINT UNIQUE(`User`, `Password`)
);