#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InterestingCalculation.Resource", IsApplication=true)]

namespace InterestingCalculation
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040009
			public const int buttonCalculate = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int buttonClear = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int editTextFinalAmount = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int editTextInitialAmount = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int editTextInterestRate = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int editTextMonthAmount = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int relativeLayout1 = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int textViewInitialAmount = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int textViewInterestRate = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int textViewNumberOfMonths = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030008
			public const int calculate = 2130903048;
			
			// aapt resource value: 0x7f030007
			public const int clear = 2130903047;
			
			// aapt resource value: 0x7f030005
			public const int decimal_standard = 2130903045;
			
			// aapt resource value: 0x7f030009
			public const int fields_cleared = 2130903049;
			
			// aapt resource value: 0x7f030004
			public const int final_amount = 2130903044;
			
			// aapt resource value: 0x7f030001
			public const int initial_amount = 2130903041;
			
			// aapt resource value: 0x7f030006
			public const int integer_standard = 2130903046;
			
			// aapt resource value: 0x7f030002
			public const int interest_rate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int months_amount = 2130903043;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
